// src/lib/themes.js

export const themes = {
  // ── LIGHT VARIANTS ──────────────────────────────────────────────
  light: {
    name: 'Light',
    mode: 'light',
    accent: '#0D9488',
    vars: {
      '--bg-base': '#F8FAFC',
      '--bg-surface': '#FFFFFF',
      '--bg-subtle': '#F1F5F9',
      '--border': '#E2E8F0',
      '--text-primary': '#111827',
      '--text-secondary': '#4B5563',
      '--text-tertiary': '#6B7280',
      '--accent': '#0D9488',
      '--accent-hover': '#0F766E',
      '--accent-subtle': '#F0FDFA',
      '--accent-text': '#0F766E',
      '--accent-text-on': '#FFFFFF',
      '--accent-text-on': '#FFFFFF',
      '--accent-text-on': '#FFFFFF',
      '--accent-text-on': '#FFFFFF',
      '--accent-text-on': '#FFFFFF',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#99F6E4',
      '--chart-bar-a': '#0D9488',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#80848A',
      '--chart-axis': '#6B7280',
      '--chart-negative': '#FCA5A5',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#CCFBF1',
      '--status-active-text': '#0F766E',
      '--status-paused-bg': '#FEF9C3',
      '--status-paused-text': '#854D0E',
      '--status-completed-bg': '#F1F5F9',
      '--status-completed-text': '#475569',
    },
  },
  'blue-light': {
    name: 'Blue Light',
    mode: 'light',
    accent: '#2563EB',
    vars: {
      '--bg-base': '#F8FAFC',
      '--bg-surface': '#FFFFFF',
      '--bg-subtle': '#F1F5F9',
      '--border': '#E2E8F0',
      '--text-primary': '#111827',
      '--text-secondary': '#4B5563',
      '--text-tertiary': '#6B7280',
      '--accent': '#2563EB',
      '--accent-hover': '#1D4ED8',
      '--accent-subtle': '#EFF6FF',
      '--accent-text': '#1D4ED8',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#BFDBFE',
      '--chart-bar-a': '#2563EB',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#80848A',
      '--chart-axis': '#6B7280',
      '--chart-negative': '#FCA5A5',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#DBEAFE',
      '--status-active-text': '#1D4ED8',
      '--status-paused-bg': '#FEF9C3',
      '--status-paused-text': '#854D0E',
      '--status-completed-bg': '#F1F5F9',
      '--status-completed-text': '#475569',
    },
  },
  'violet-light': {
    name: 'Violet Light',
    mode: 'light',
    accent: '#7C3AED',
    vars: {
      '--bg-base': '#F8FAFC',
      '--bg-surface': '#FFFFFF',
      '--bg-subtle': '#F1F5F9',
      '--border': '#E2E8F0',
      '--text-primary': '#111827',
      '--text-secondary': '#4B5563',
      '--text-tertiary': '#6B7280',
      '--accent': '#7C3AED',
      '--accent-hover': '#6D28D9',
      '--accent-subtle': '#F5F3FF',
      '--accent-text': '#6D28D9',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#DDD6FE',
      '--chart-bar-a': '#7C3AED',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#80848A',
      '--chart-axis': '#6B7280',
      '--chart-negative': '#FCA5A5',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#EDE9FE',
      '--status-active-text': '#6D28D9',
      '--status-paused-bg': '#FEF9C3',
      '--status-paused-text': '#854D0E',
      '--status-completed-bg': '#F1F5F9',
      '--status-completed-text': '#475569',
    },
  },
  'rose-light': {
    name: 'Rose Light',
    mode: 'light',
    accent: '#E11D48',
    vars: {
      '--bg-base': '#F8FAFC',
      '--bg-surface': '#FFFFFF',
      '--bg-subtle': '#F1F5F9',
      '--border': '#E2E8F0',
      '--text-primary': '#111827',
      '--text-secondary': '#4B5563',
      '--text-tertiary': '#6B7280',
      '--accent': '#E11D48',
      '--accent-hover': '#BE123C',
      '--accent-subtle': '#FFF1F2',
      '--accent-text': '#BE123C',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#FECDD3',
      '--chart-bar-a': '#E11D48',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#80848A',
      '--chart-axis': '#6B7280',
      '--chart-negative': '#FB923C',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#FFE4E6',
      '--status-active-text': '#BE123C',
      '--status-paused-bg': '#FEF9C3',
      '--status-paused-text': '#854D0E',
      '--status-completed-bg': '#F1F5F9',
      '--status-completed-text': '#475569',
    },
  },
  'amber-light': {
    name: 'Amber Light',
    mode: 'light',
    accent: '#D97706',
    vars: {
      '--bg-base': '#F8FAFC',
      '--bg-surface': '#FFFFFF',
      '--bg-subtle': '#F1F5F9',
      '--border': '#E2E8F0',
      '--text-primary': '#111827',
      '--text-secondary': '#4B5563',
      '--text-tertiary': '#6B7280',
      '--accent': '#D97706',
      '--accent-hover': '#B45309',
      '--accent-subtle': '#FFFBEB',
      '--accent-text': '#B45309',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#FDE68A',
      '--chart-bar-a': '#D97706',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#80848A',
      '--chart-axis': '#6B7280',
      '--chart-negative': '#FCA5A5',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#FEF3C7',
      '--status-active-text': '#B45309',
      '--status-paused-bg': '#FEF9C3',
      '--status-paused-text': '#854D0E',
      '--status-completed-bg': '#F1F5F9',
      '--status-completed-text': '#475569',
    },
  },

  // ── DARK VARIANTS ───────────────────────────────────────────────
  dark: {
    name: 'Dark',
    mode: 'dark',
    accent: '#0D9488',
    vars: {
      '--bg-base': '#0F172A',
      '--bg-surface': '#1E293B',
      '--bg-subtle': '#334155',
      '--border': '#334155',
      '--text-primary': '#F1F5F9',
      '--text-secondary': '#CBD5E1',
      '--text-tertiary': '#94A3B8',
      '--accent': '#0D9488',
      '--accent-hover': '#14B8A6',
      '--accent-subtle': '#134E4A',
      '--accent-text': '#5EEAD4',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#0F766E',
      '--chart-bar-a': '#0D9488',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#475569',
      '--chart-axis': '#94A3B8',
      '--chart-negative': '#F87171',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#134E4A',
      '--status-active-text': '#5EEAD4',
      '--status-paused-bg': '#451A03',
      '--status-paused-text': '#FCD34D',
      '--status-completed-bg': '#1E293B',
      '--status-completed-text': '#94A3B8',
    },
  },
  'soft-dark': {
    name: 'Soft Dark',
    mode: 'dark',
    accent: '#0D9488',
    vars: {
      '--bg-base': '#1C1C1E',
      '--bg-surface': '#2C2C2E',
      '--bg-subtle': '#3A3A3C',
      '--border': '#48484A',
      '--text-primary': '#F2F2F7',
      '--text-secondary': '#AEAEB2',
      '--text-tertiary': '#8E8E93',
      '--accent': '#0D9488',
      '--accent-hover': '#14B8A6',
      '--accent-subtle': '#1C3330',
      '--accent-text': '#5EEAD4',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#0F766E',
      '--chart-bar-a': '#0D9488',
      '--chart-bar-b': '#AEAEB2',
      '--chart-grid': '#48484A',
      '--chart-axis': '#8E8E93',
      '--chart-negative': '#F87171',
      '--chart-positive-b': '#AEAEB2',
      '--status-active-bg': '#1C3330',
      '--status-active-text': '#5EEAD4',
      '--status-paused-bg': '#3A2800',
      '--status-paused-text': '#FCD34D',
      '--status-completed-bg': '#2C2C2E',
      '--status-completed-text': '#8E8E93',
    },
  },
  'high-contrast': {
    name: 'High Contrast',
    mode: 'dark',
    accent: '#00FFD4',
    vars: {
      '--bg-base': '#000000',
      '--bg-surface': '#111111',
      '--bg-subtle': '#1A1A1A',
      '--border': '#333333',
      '--text-primary': '#FFFFFF',
      '--text-secondary': '#E0E0E0',
      '--text-tertiary': '#AAAAAA',
      '--accent': '#00FFD4',
      '--accent-hover': '#00E5BC',
      '--accent-subtle': '#003D35',
      '--accent-text': '#00FFD4',
      '--accent-text-on': '#000000',
      '--accent-border': '#00A896',
      '--chart-bar-a': '#00FFD4',
      '--chart-bar-b': '#AAAAAA',
      '--chart-grid': '#333333',
      '--chart-axis': '#AAAAAA',
      '--chart-negative': '#FF6B6B',
      '--chart-positive-b': '#AAAAAA',
      '--status-active-bg': '#003D35',
      '--status-active-text': '#00FFD4',
      '--status-paused-bg': '#3D2800',
      '--status-paused-text': '#FFD700',
      '--status-completed-bg': '#1A1A1A',
      '--status-completed-text': '#AAAAAA',
    },
  },
  'blue-dark': {
    name: 'Blue Dark',
    mode: 'dark',
    accent: '#3B82F6',
    vars: {
      '--bg-base': '#0F172A',
      '--bg-surface': '#1E293B',
      '--bg-subtle': '#334155',
      '--border': '#334155',
      '--text-primary': '#F1F5F9',
      '--text-secondary': '#CBD5E1',
      '--text-tertiary': '#94A3B8',
      '--accent': '#3B82F6',
      '--accent-hover': '#60A5FA',
      '--accent-subtle': '#1E3A5F',
      '--accent-text': '#93C5FD',
      '--accent-text-on': '#FFFFFF',
      '--accent-border': '#1D4ED8',
      '--chart-bar-a': '#3B82F6',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#475569',
      '--chart-axis': '#94A3B8',
      '--chart-negative': '#F87171',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#1E3A5F',
      '--status-active-text': '#93C5FD',
      '--status-paused-bg': '#451A03',
      '--status-paused-text': '#FCD34D',
      '--status-completed-bg': '#1E293B',
      '--status-completed-text': '#94A3B8',
    },
  },
  'violet-dark': {
    name: 'Violet Dark',
    mode: 'dark',
    accent: '#A78BFA',
    vars: {
      '--bg-base': '#0F0A1E',
      '--bg-surface': '#1A1033',
      '--bg-subtle': '#2D1F50',
      '--border': '#3D2B6B',
      '--text-primary': '#F1F5F9',
      '--text-secondary': '#CBD5E1',
      '--text-tertiary': '#94A3B8',
      '--accent': '#A78BFA',
      '--accent-hover': '#C4B5FD',
      '--accent-subtle': '#2D1F50',
      '--accent-text': '#C4B5FD',
      '--accent-text-on': '#1A1033',
      '--accent-border': '#7C3AED',
      '--chart-bar-a': '#A78BFA',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#3D2B6B',
      '--chart-axis': '#94A3B8',
      '--chart-negative': '#F87171',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#2D1F50',
      '--status-active-text': '#C4B5FD',
      '--status-paused-bg': '#451A03',
      '--status-paused-text': '#FCD34D',
      '--status-completed-bg': '#1A1033',
      '--status-completed-text': '#94A3B8',
    },
  },
  'rose-dark': {
    name: 'Rose Dark',
    mode: 'dark',
    accent: '#FB7185',
    vars: {
      '--bg-base': '#1A0A0F',
      '--bg-surface': '#2D1520',
      '--bg-subtle': '#3D1F2C',
      '--border': '#5C2D3E',
      '--text-primary': '#F1F5F9',
      '--text-secondary': '#CBD5E1',
      '--text-tertiary': '#94A3B8',
      '--accent': '#FB7185',
      '--accent-hover': '#FDA4AF',
      '--accent-subtle': '#3D1F2C',
      '--accent-text': '#FDA4AF',
      '--accent-text-on': '#1A0A0F',
      '--accent-border': '#E11D48',
      '--chart-bar-a': '#FB7185',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#5C2D3E',
      '--chart-axis': '#94A3B8',
      '--chart-negative': '#FB923C',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#3D1F2C',
      '--status-active-text': '#FDA4AF',
      '--status-paused-bg': '#451A03',
      '--status-paused-text': '#FCD34D',
      '--status-completed-bg': '#2D1520',
      '--status-completed-text': '#94A3B8',
    },
  },
  'amber-dark': {
    name: 'Amber Dark',
    mode: 'dark',
    accent: '#FBBF24',
    vars: {
      '--bg-base': '#1A1200',
      '--bg-surface': '#2D1F00',
      '--bg-subtle': '#3D2C00',
      '--border': '#5C4200',
      '--text-primary': '#F1F5F9',
      '--text-secondary': '#CBD5E1',
      '--text-tertiary': '#94A3B8',
      '--accent': '#FBBF24',
      '--accent-hover': '#FCD34D',
      '--accent-subtle': '#3D2C00',
      '--accent-text': '#FCD34D',
      '--accent-text-on': '#111827',
      '--accent-border': '#D97706',
      '--chart-bar-a': '#FBBF24',
      '--chart-bar-b': '#94A3B8',
      '--chart-grid': '#5C4200',
      '--chart-axis': '#94A3B8',
      '--chart-negative': '#F87171',
      '--chart-positive-b': '#94A3B8',
      '--status-active-bg': '#3D2C00',
      '--status-active-text': '#FCD34D',
      '--status-paused-bg': '#451A03',
      '--status-paused-text': '#FCD34D',
      '--status-completed-bg': '#2D1F00',
      '--status-completed-text': '#94A3B8',
    },
  },
}

export const defaultTheme = 'light'

export function applyTheme(themeKey) {
  const theme = themes[themeKey] ?? themes[defaultTheme]
  const root = document.documentElement
  Object.entries(theme.vars).forEach(([key, value]) => {
    root.style.setProperty(key, value)
  })
  localStorage.setItem('pulsesdk_theme', themeKey)
}

export function getStoredTheme() {
  return localStorage.getItem('pulsesdk_theme') ?? defaultTheme
}

// Helper to read a CSS variable value at runtime (for Recharts)
export function cssVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim()
}